name: PR Merged
on:
  pull_request:
    types: [closed]
  push:
    branches:
      main
jobs:
  update-task:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update task in Repo A
        run: |
          # Install necessary dependencies
          sudo apt-get install jq curl
          
          # Get the number of the current PR
          PR_NUMBER=1 #${{ github.event.pull_request.number }}

          # Get the repository where the current PR is located
          REPO=${{ github.repository }}

          # Get the API URL of the current PR
          API_URL="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/timeline"

          # Get the timeline (comments) of the current PR
          TIMELINE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $API_URL)
          
          # Parse the comments to get the ones that mention the PR
          TASK_URL=$(echo $TIMELINE | jq '.[1] | .source.issue.pull_request.url')
          
          TASK_BODY=$(echo $TIMELINE | jq '.[1] | .source.issue.body')
          UPDATED_TASK_BODY=$(echo $TASK_BODY | sed 's/- \[ \]/- \[x\]/')
          echo $TASK_URL
          echo $UPDATED_TASK_BODY
          # TASK_URL_ENCODED=$(urlencode "$TASK_URL")
          # echo $TASK_URL_ENCODED
          # Update the task comment
          curl -v -L \"$TASK_URL\"
          # curl -L \
          # -X PATCH \
          # -H "Accept: application/vnd.github+json" \
          # -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # '$TASK_URL' \
          # -d '{\"body\": \"$UPDATED_TASK_BODY\"}'
