name: PR Merged
on:
  pull_request:
    types: [closed]
  push:
    branches:
      main

jobs:
  update-task:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update task in Repo A
        run: |
          # Install necessary dependencies
          sudo apt-get install jq curl
          
          # Get the number of the current PR
          PR_NUMBER=1 #${{ github.event.pull_request.number }}
          # echo $PR_NUMBER
          # Get the repository where the current PR is located
          REPO=${{ github.repository }}
          echo $REPO
          # Get the API URL of the current PR
          API_URL="https://api.github.com/repos/$REPO/issues/$PR_NUMBER/timeline"
          echo $API_URL
          # Get the comments of the current PR
          TIMELINE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $API_URL)
          
          # Parse the comments to get the ones that mention a PR in Repo A
          TASK_COMMENTS=$(echo $TIMELINE | jq '.[1] | .source.issue.pull_request.url')
          echo $TASK_COMMENTS
          TASK_BODY=$(echo $TIMELINE | jq '.[1] | .source.issue.body')
          echo $TASK_BODY
          UPDATED_TASK_BODY=$(echo $TASK_BODY | sed 's/- \[ \]/- \[x\]/')
          echo $UPDATED_TASK_BODY
          
          # # Loop over the task comments
          # echo $TASK_COMMENTS | jq -r '.[] | @base64' | while read TASK_COMMENT; do
          #   TASK_COMMENT=$(echo $TASK_COMMENT | base64 --decode)
            
          #   # Get the API URL of the task comment
          #   TASK_API_URL=$(echo $TASK_COMMENT | jq -r '.url')
          #   echo $TASK_API_URL
            
          #   # Get the body of the task comment
          #   TASK_BODY=$(echo $TASK_COMMENT | jq -r '.body')
          #   echo $TASK_BODY
            
          #   # Replace the checkbox with a checked checkbox
          #   UPDATED_TASK_BODY=$(echo $TASK_BODY | sed 's/- \[ \]/- \[x\]/')
          #   echo $UPDATED_TASK_BODY
            
            # Update the task comment
            echo "curling"
            echo $TASK_COMMENTS
            # curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\": \"$UPDATED_TASK_BODY\"}" $TASK_COMMENTS
            curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "$TASK_COMMENTS" \
            -d '{"title": "feat(pr): add file to create a PR","body": "$UPDATED_TASK_BODY","state":"open"}'
          done

